import json
import os
from agent.mcp_client.session import call_mcp, wake_up_server
from agent.storage import get_connection, update_run_status
from dotenv import load_dotenv

load_dotenv()


def publish_to_docs(run_id: str, summary: dict) -> str:
    """
    Append weekly pulse report to Google Doc via MCP server.
    Returns the doc URL.
    Idempotent — skips if section already exists.
    """
    doc_id = os.getenv("GOOGLE_DOC_ID", "")
    if not doc_id:
        raise RuntimeError(
            "GOOGLE_DOC_ID not set in .env. "
            "Create a Google Doc and add its ID."
        )

    product = summary.get("product", "groww")
    week = summary.get("week", "")
    anchor = f"pulse-{product}-{week}"

    # Build rich report content
    content = build_doc_content(run_id, summary)

    # Wake up MCP server
    wake_up_server()

    print(f"  Appending report to Google Doc...")
    print(f"  Doc ID: {doc_id}")
    print(f"  Anchor: {anchor}")

    # Call MCP server to append
    response = call_mcp("/append_to_doc", {
        "doc_id": doc_id,
        "content": content,
        "anchor": anchor,
    })

    doc_url = f"https://docs.google.com/document/d/{doc_id}/edit"

    # Update run status
    conn = get_connection()
    conn.execute(
        "UPDATE runs SET gdoc_id = ?, status = ?, updated_at = datetime('now') WHERE id = ?",
        (doc_id, "published_docs", run_id),
    )
    conn.commit()
    conn.close()

    print(f"  ✓ Report appended to Google Doc")
    print(f"  Doc URL: {doc_url}")

    return doc_url


def build_doc_content(run_id: str, summary: dict) -> str:
    """Build rich detailed text content for Google Doc"""
    product = summary.get("product", "groww").title()
    week = summary.get("week", "")
    themes = summary.get("themes", [])
    action_ideas = summary.get("action_ideas", [])
    total_reviews = summary.get("total_reviews_analyzed", 0)

    # Get source breakdown from database
    conn = get_connection()
    sources = conn.execute(
        """
        SELECT source, COUNT(*) as count
        FROM reviews
        WHERE product = ?
        GROUP BY source
        """,
        (summary.get("product", "groww"),),
    ).fetchall()

    # Get keyphrases for each theme
    theme_keyphrases = {}
    for theme in themes:
        row = conn.execute(
            "SELECT keyphrases_json FROM themes WHERE run_id = ? AND rank = ?",
            (run_id, theme["rank"]),
        ).fetchone()
        if row:
            theme_keyphrases[theme["rank"]] = json.loads(row[0])
    conn.close()

    # Calculate urgency scores
    max_count = max((t["review_count"] for t in themes), default=1)

    lines = []

    # Separator
    lines.append("=" * 60)
    lines.append("")

    # Header
    lines.append(f"GROWW WEEKLY APP PULSE — {week}")
    lines.append(f"Generated automatically by Review Pulse Agent")
    lines.append("")

    # Stats
    lines.append("OVERVIEW")
    lines.append(f"Total reviews analyzed: {total_reviews}")
    for source, count in sources:
        lines.append(f"  • {source.title()}: {count} reviews")
    lines.append(f"Themes discovered: {len(themes)}")
    lines.append("")

    # All themes (not just top 3)
    lines.append("ALL THEMES THIS WEEK")
    lines.append("")

    for theme in themes:
        urgency = min(9.5, round((theme['review_count'] / max_count) * 10, 1))
        lines.append(f"{theme['rank']}. {theme['name']}")
        lines.append(f"   Reviews: {theme['review_count']} | Urgency: {urgency}/10")

        # Keyphrases
        keyphrases = theme_keyphrases.get(theme['rank'], [])
        if keyphrases:
            lines.append(f"   Key signals: {', '.join(keyphrases[:5])}")

        # Quote
        quote = theme.get("quote", "")
        if quote:
            lines.append(f'   User quote: "{quote}"')
        lines.append("")

    # Action Ideas
    lines.append("ACTION IDEAS FOR PRODUCT TEAM")
    lines.append("")
    for i, idea in enumerate(action_ideas, 1):
        lines.append(f"{i}. {idea}")
    lines.append("")

    # Footer
    lines.append("---")
    lines.append("Source: Public app store reviews (Play Store + App Store)")
    lines.append("Facts only. No investment advice. No PII collected.")
    lines.append("Generated by Groww Review Pulse Agent")
    lines.append("")

    return "\n".join(lines)