import json
import os
from agent.mcp_client.session import call_mcp, wake_up_server
from agent.storage import get_connection, update_run_status
from dotenv import load_dotenv

load_dotenv()


def publish_to_docs(run_id: str, summary: dict) -> str:
    """
    Append weekly pulse report to Google Doc via MCP server.
    Returns the doc URL.
    Idempotent — skips if section already exists.
    """
    doc_id = os.getenv("GOOGLE_DOC_ID", "")
    if not doc_id:
        raise RuntimeError(
            "GOOGLE_DOC_ID not set in .env. "
            "Create a Google Doc and add its ID."
        )

    product = summary.get("product", "groww")
    week = summary.get("week", "")
    themes = summary.get("themes", [])
    action_ideas = summary.get("action_ideas", [])

    # Build report content
    content = build_doc_content(summary)

    # Wake up MCP server
    wake_up_server()

    # Check idempotency — look for existing section
    anchor = f"pulse-{product}-{week}"

    print(f"  Appending report to Google Doc...")
    print(f"  Doc ID: {doc_id}")
    print(f"  Anchor: {anchor}")

    # Call MCP server to append
    response = call_mcp("/append_to_doc", {
        "doc_id": doc_id,
        "content": content,
        "anchor": anchor,
    })

    doc_url = f"https://docs.google.com/document/d/{doc_id}/edit"

    # Update run status
    conn = get_connection()
    conn.execute(
        "UPDATE runs SET gdoc_id = ?, status = ?, updated_at = datetime('now') WHERE id = ?",
        (doc_id, "published_docs", run_id),
    )
    conn.commit()
    conn.close()

    print(f"  ✓ Report appended to Google Doc")
    print(f"  Doc URL: {doc_url}")

    return doc_url


def build_doc_content(summary: dict) -> str:
    """Build formatted text content for Google Doc"""
    product = summary.get("product", "groww").title()
    week = summary.get("week", "")
    themes = summary.get("themes", [])
    action_ideas = summary.get("action_ideas", [])
    total_reviews = summary.get("total_reviews_analyzed", 0)

    lines = []
    lines.append(f"Groww Weekly Review Pulse — {week}")
    lines.append(f"Reviews analyzed: {total_reviews}")
    lines.append("")
    lines.append("TOP THEMES")
    lines.append("")

    for theme in themes[:3]:
        lines.append(f"{theme['rank']}. {theme['name']} ({theme['review_count']} reviews)")
        quote = theme.get("quote", "")
        if quote:
            lines.append(f'   "{quote}"')
        lines.append("")

    lines.append("ACTION IDEAS")
    lines.append("")
    for i, idea in enumerate(action_ideas, 1):
        lines.append(f"{i}. {idea}")

    lines.append("")
    lines.append("---")
    lines.append("Generated by Groww Review Pulse Agent")
    lines.append("Facts only. No investment advice.")

    return "\n".join(lines)