import os
from jinja2 import Template

HTML_TEMPLATE = """<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <style>
        body { font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; color: #333; }
        .header { background: #00b386; color: white; padding: 20px; border-radius: 8px 8px 0 0; }
        .header h1 { margin: 0; font-size: 20px; }
        .header p { margin: 5px 0 0; font-size: 13px; opacity: 0.9; }
        .content { padding: 20px; background: #f9f9f9; }
        .theme { background: white; border-left: 4px solid #00b386; padding: 12px 16px; margin: 12px 0; border-radius: 0 8px 8px 0; }
        .theme h3 { margin: 0 0 6px; font-size: 15px; color: #1a1a2e; }
        .theme .count { font-size: 12px; color: #888; }
        .quote { font-style: italic; color: #555; font-size: 13px; margin: 8px 0 0; border-left: 2px solid #ddd; padding-left: 10px; }
        .actions { background: white; padding: 16px; border-radius: 8px; margin: 16px 0; }
        .actions h2 { font-size: 16px; color: #1a1a2e; margin: 0 0 12px; }
        .action-item { padding: 8px 0; border-bottom: 1px solid #f0f0f0; font-size: 14px; }
        .action-item:last-child { border-bottom: none; }
        .cta { text-align: center; padding: 20px; }
        .cta a { background: #00b386; color: white; padding: 12px 24px; border-radius: 6px; text-decoration: none; font-weight: bold; }
        .footer { padding: 16px; font-size: 11px; color: #999; text-align: center; }
        .stats { font-size: 12px; color: #888; margin-bottom: 16px; }
    </style>
</head>
<body>
    <div class="header">
        <h1>📊 Groww Weekly Review Pulse</h1>
        <p>Week {{ week }} · {{ total_reviews }} reviews analyzed</p>
    </div>
    <div class="content">
        <p class="stats">Here's what Groww users are saying this week across Play Store and App Store.</p>

        <h2 style="font-size:16px; color:#1a1a2e;">Top Themes</h2>
        {% for theme in themes %}
        <div class="theme">
            <h3>{{ loop.index }}. {{ theme.name }}</h3>
            <span class="count">{{ theme.review_count }} reviews</span>
            {% if theme.quote %}
            <p class="quote">"{{ theme.quote }}"</p>
            {% endif %}
        </div>
        {% endfor %}

        <div class="actions">
            <h2>💡 Action Ideas</h2>
            {% for idea in action_ideas %}
            <div class="action-item">{{ loop.index }}. {{ idea }}</div>
            {% endfor %}
        </div>

        <div class="cta">
            <a href="{{ doc_deep_link }}">📄 Read Full Report in Google Docs</a>
        </div>
    </div>
    <div class="footer">
        <p>⚠️ This report is generated from public app store reviews for informational purposes only.</p>
        <p>Generated by Groww Review Pulse Agent · {{ week }}</p>
    </div>
</body>
</html>"""

TEXT_TEMPLATE = """Subject: [Weekly Pulse] Groww — {{ week }} — {{ top_theme }}

Groww Weekly Review Pulse
Week: {{ week }} | Reviews analyzed: {{ total_reviews }}

TOP THEMES
{% for theme in themes %}{{ loop.index }}. {{ theme.name }} ({{ theme.review_count }} reviews)
   "{{ theme.quote }}"

{% endfor %}
ACTION IDEAS
{% for idea in action_ideas %}{{ loop.index }}. {{ idea }}
{% endfor %}

Read full report: {{ doc_deep_link }}

---
This report is generated from public app store reviews for informational purposes only.
Generated by Groww Review Pulse Agent.
"""


def render_email(
    summary: dict,
    doc_deep_link: str = "{DOC_DEEP_LINK}",
) -> tuple[str, str]:
    """
    Render HTML and plain text email from PulseSummary.
    Returns (html_content, text_content)
    """
    themes = summary.get("themes", [])
    action_ideas = summary.get("action_ideas", [])
    week = summary.get("week", "")
    total_reviews = summary.get("total_reviews_analyzed", 0)
    top_theme = themes[0]["name"] if themes else "Weekly Update"

    # Render HTML
    html_tmpl = Template(HTML_TEMPLATE)
    html_content = html_tmpl.render(
        week=week,
        total_reviews=total_reviews,
        themes=themes[:3],
        action_ideas=action_ideas,
        doc_deep_link=doc_deep_link,
    )

    # Render plain text
    text_tmpl = Template(TEXT_TEMPLATE)
    text_content = text_tmpl.render(
        week=week,
        total_reviews=total_reviews,
        themes=themes[:3],
        action_ideas=action_ideas,
        doc_deep_link=doc_deep_link,
        top_theme=top_theme,
    )

    return html_content, text_content


def get_email_subject(summary: dict) -> str:
    """Generate email subject line"""
    week = summary.get("week", "")
    themes = summary.get("themes", [])
    top_theme = themes[0]["name"] if themes else "Weekly Update"
    return f"[Weekly Pulse] Groww — {week} — {top_theme}"